# Generated by Django 5.2.6 on 2025-09-30 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [



        migrations.CreateModel(
            name='Kostentyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schuleinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schulklasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('anzahl_schueler', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lizenznehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schuleinheit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lizenzen.schuleinheit')),
            ],
        ),
        migrations.CreateModel(
            name='Verwaltung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lizenz_start', models.DateField()),
                ('lizenz_ende', models.DateField()),
                ('anzahl_weitere_lizenzen', models.PositiveIntegerField()),
                ('kostentyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lizenzen.kostentyp')),
                ('lizenznehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lizenzen.lizenznehmer')),
                ('schulklasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lizenzen.schulklasse')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lizenzen.software')),
            ],
        ),
    ]
