# Generated by Django 5.2.6 on 2025-10-05 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lizenzen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kostentyp',
            options={'ordering': ['bezeichnung'], 'verbose_name': 'Kostentyp', 'verbose_name_plural': 'Kostentypen'},
        ),
        migrations.AlterModelOptions(
            name='lizenznehmer',
            options={'ordering': ['name'], 'verbose_name': 'Lizenznehmer', 'verbose_name_plural': 'Lizenznehmer'},
        ),
        migrations.AlterModelOptions(
            name='schuleinheit',
            options={'ordering': ['bezeichnung'], 'verbose_name': 'Schuleinheit', 'verbose_name_plural': 'Schuleinheiten'},
        ),
        migrations.AlterModelOptions(
            name='schulklasse',
            options={'ordering': ['name'], 'verbose_name': 'Schulklasse', 'verbose_name_plural': 'Schulklassen'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['name'], 'verbose_name': 'Software', 'verbose_name_plural': 'Software'},
        ),
        migrations.AlterModelOptions(
            name='verwaltung',
            options={'ordering': ['lizenznehmer', 'software'], 'verbose_name': 'Lizenzverwaltung', 'verbose_name_plural': 'Lizenzverwaltungen'},
        ),
        migrations.AlterField(
            model_name='kostentyp',
            name='bezeichnung',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lizenznehmer',
            name='schuleinheit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lizenznehmer', to='lizenzen.schuleinheit'),
        ),
        migrations.AlterField(
            model_name='schuleinheit',
            name='bezeichnung',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='schulklasse',
            name='anzahl_schueler',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schulklasse',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verwaltung',
            name='anzahl_weitere_lizenzen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
